Repository WildCodeSchool-CDA-FT-2024-09/JS-CDA-Projet-1-Team-B, pull requests merged in 2024-10, with the labels that each got.

#1 Repo config
  .gitignore
  .husky/pre-commit
  README.md
  api/.env.sample
  api/.gitignore
  api/.prettierrc
  api/eslint.config.mjs
  api/index.ts
  api/package-lock.json
  api/package.json
  api/public/.gitkeep
  api/src/data/.gitkeep
  api/src/db/data-source.ts
  api/src/db/db.sqlite
  api/src/entities/.gitkeep
  api/src/resolvers/.gitkeep
  api/src/services/.gitkeep
  api/src/types/.gitkeep
  api/tsconfig.json
  client/.env.sample
  client/.gitignore
  client/README.md
  client/eslint.config.js
  client/index.html
  client/package-lock.json
  client/package.json
  client/postcss.config.js
  client/public/thrillermania.png
  client/public/thrillermania.svg
  client/src/App.tsx
  client/src/assets/.gitkeep
  client/src/components/TestHolder.tsx
  client/src/generated/.gitkeep
  client/src/index.css
  client/src/main.tsx
  client/src/pages/Page.tsx
  client/src/schema/.gitkeep
  client/src/services/codegen.ts
  client/src/services/connection.ts
  client/src/types/.gitkeep
  client/src/vite-env.d.ts
  client/tailwind.config.js
  client/tsconfig.app.json
  client/tsconfig.json
  client/tsconfig.node.json
  client/vite.config.ts
  package-lock.json
  package.json
Labels: REVIEWED

#2 Ajout des fichiers seed, fetch et create pour reset et peupler la bdd avec l'api
  api/.env.sample
  api/package-lock.json
  api/package.json
  api/src/data/.gitkeep
  api/src/data/create.ts
  api/src/data/fetch.ts
  api/src/db/data-source.ts
  api/src/db/db.sqlite
  api/src/entities/.gitkeep
  api/src/entities/Film.ts
  api/src/types/.gitkeep
  api/src/types/film.types.ts
Labels: REVIEW REQUESTED

#4 Feature/carroussel trendy films
  .gitignore
  api/.gitignore
  api/index.ts
  api/src/entities/Film.ts
  api/src/resolvers/FilmResolver.ts
  client/public/Sequence diagram carroussel Trendy -2024-10-23-140753.png
  client/src/App.tsx
  client/src/components/CarrousselTrendyFilms.tsx
  client/src/generated/graphql-types.ts
  client/src/index.css
  client/src/main.tsx
  client/src/pages/HomePage.tsx
  client/src/schema/queries/getTrendyFilms.ts
  client/src/services/codegen.ts
  client/tailwind.config.js
Labels: CORRECTIONS DONE

#3 Ajout du composant SearchBar avec requête GraphQL pour la recherche de films
  api/src/data/create.ts
  api/src/data/fetch.ts
  api/src/enums/Criteria.ts
  api/src/resolvers/FilmResolver.ts
  api/src/types/film.types.ts
  client/index.html
  client/public/search.svg
  client/src/App.tsx
  client/src/components/SearchBar.tsx
  client/src/generated/.gitkeep
  client/src/generated/graphql-types.ts
  client/src/index.css
  client/src/main.tsx
  client/src/pages/HomePage.tsx
  client/src/schema/queries/searchFilms.ts
  client/src/services/codegen.ts
  client/tailwind.config.js
Labels: REVIEWED

#7 Ajout de la colonne tmdbId dans l'entity Film + ajout de la possibili…
  api/src/data/create.ts
  api/src/entities/Film.ts
Labels: REVIEWED

#5 Page detail feature/add film detail
  api/.gitignore
  api/src/resolvers/FilmResolver.ts
  client/src/components/NoteGlobale.tsx
  client/src/generated/graphql-types.ts
  client/src/main.tsx
  client/src/pages/PageFilmDetail.tsx
  client/src/schema/searchFilmById.ts
  client/src/services/codegen.ts
Labels: REVIEWED

#6 Feature/signup signin page
  api/.gitignore
  api/index.ts
  api/package-lock.json
  api/package.json
  api/src/data/create.ts
  api/src/db/data-source.ts
  api/src/entities/Avatar.ts
  api/src/entities/Film.ts
  api/src/entities/User.ts
  api/src/resolvers/AvatarResolver.ts
  api/src/resolvers/UserResolver.ts
  client/.gitignore
  client/codegen.ts
  client/package-lock.json
  client/package.json
  client/src/components/SignIn.tsx
  client/src/components/SignUp.tsx
  client/src/components/TestHolder.tsx
  client/src/generated/graphql-types.ts
  client/src/index.css
  client/src/main.tsx
  client/src/schema/mutations/.gitkeep
  client/src/schema/mutations/SignUp.ts
  client/src/schema/queries/.gitkeep
  client/src/schema/queries/SignIn.ts
  client/src/types/SignIn.types.ts
  client/src/types/SignUp.types.ts
  client/tsconfig.app.json
Labels: REVIEWED
